"""プロンプトテンプレート"""

from src.prompts.supervisor_prompt import SUPERVISOR_PLANNING_PROMPT, SUPERVISOR_ROUTING_PROMPT
from src.prompts.writer_prompt import WRITER_SYSTEM_PROMPT, WRITER_USER_PROMPT
from src.prompts.reviewer_prompt import REVIEWER_SYSTEM_PROMPT, REVIEWER_USER_PROMPT

__all__ = [
    "SUPERVISOR_PLANNING_PROMPT",
    "SUPERVISOR_ROUTING_PROMPT",
    "WRITER_SYSTEM_PROMPT",
    "WRITER_USER_PROMPT",
    "REVIEWER_SYSTEM_PROMPT",
    "REVIEWER_USER_PROMPT"
]

